name: Publish NuGet Package

on:
  pull_request:
    branches:
      - master
    types: [ closed ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref || github.ref_name, 'release/')
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set tag environment
        run: echo "TAG=${BRANCH_NAME##*/}" >> $GITHUB_ENV

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TrickOrTreat/TrickOrTreat.csproj

      - name: Build project
        run: dotnet build TrickOrTreat/TrickOrTreat.csproj --configuration Release --no-restore

      - name: Create NuGet package
        run: dotnet pack TrickOrTreat/TrickOrTreat.csproj /p:PackageVersion=${{ env.TAG }} --configuration Release --no-build -o ./nupkg

      - name: Add GitHub Packages as NuGet source
        run: |
          dotnet nuget add source \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Publish NuGet Package to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
